### ISSUE TITLE
Failed obtaining connection

### ISSUE THREAD

**Issue by xushirain** [jcs47/hyperledger-bftsmart#33] opened 2018-10-16 09:13 UTC
hello,i'm testing the "Executing the ordering service outside docker v1.2",after I execute "./.build/bin/peer node start",the peer terminal show
![image](https://user-images.githubusercontent.com/17526065/47005583-a29f0500-d166-11e8-8ea7-379f693e9402.png)
i don't know how to fix it.

**Comment by jcs47** [comment] 2018-10-16 14:29
Based on the logs, the cause of the problem is the fact that I forgot to mention a step. Basically it is necessary to edit the configtx.yaml file before creating the genesis block so that it includes a valid endpoint to the frontend. Here it is the instruction that was missing from the guide:

> The first step is to generate the genesis block for the ordering service. Make sure the parameter `Orderer->Addresses` in the `./fabric/sampleconfig/configtx.yaml` file is set to `- 127.0.0.1:7050`. Next, generate the block as follows:

**Comment by xushirain** [comment] 2018-10-17 02:44
Fitrst,thx for your reply.
The same error has occurred since I edited the configtx.yaml
![image](https://user-images.githubusercontent.com/17526065/47057998-b3e32280-d1f5-11e8-9174-43047e0363bc.png)
But the problem was eventually solved.
Actually,when I clear out /var/hyperledger/production/, that error does not appear, and there is no problem with subsequent operations.

**Comment by jcs47** [comment] 2018-10-17 02:49
Yeah, it is necessary to either purge the peer's state or issue a reconfiguration transaction to update the configuration block. Closing the issue then.

**Closed as completed by jcs47** 2018-10-17 02:49 UTC
